### ISSUE TITLE
Greenslit-Review

### ISSUE THREAD

**Issue by Nwgreen6283** [hayhem/HAYLEYHEMME-MADA-project#2]
Hey Hayley!

Really great job overall with your project so far. Each of your scripts had clear annotations of why you were running each chunk, which made it helpful to follow along. Having each code labeled with a number for order made the flow intuitive and organized. Also, I am a huge fan of your PCA plots that you produced. Those are something that I want to integrate into my reserach, so it was nice seeing how your code worked. 

I have a few notes:
- It might be nice to add a main README to the main project file, that briefly reviews the structure of your repo. 
- You still have a Slides template in your repo
- Processing Code: I ran into a few errors in the cleaning 2022 code (lines 45-46 and 116-117) and cleaning race code (line 15). 
- Analysis Code: Error in p3 code (line 159)-- "could not find connection".  and in sex code (line 59). 

Some of these errors had to do with the join_by() function. But I am not sure why it could not find the function since tidyverse and dplyr were installed. 

It would be helpful to add interpretation to some of your plots (a sentence or two) and add these plus the plot to your manuscript. While you have your Data description and hypotheses, it would be good to add to the other sections of your manuscript.  

Overall, this was mostly reproducible, but had a few of these components missing/codes that did not run. Other than those issues, everything looked really great, ran well, and was clear. 
**Score: 2/3**

**Comment by hayhem** [comment]
Hi Nathan,

I appreciate your feedback! It was my first time trying to use PCA. It was definitely an interesting process, and I hope seeing my example is useful for you in the future! Something that I'm hoping to figure out is if it's possible to `facet` for specific variables, in my case, race/ethnicity. I'm not entirely sure the usefulness of this aside from save some lines of code, but the primary reason that I created the PCA_function was to concisely perform these steps by race/ethnicity. 

Good eye on the slides template! I removed it from repo.  :)

I wasn't able to replicate the issues you ran into with join_by on my computer. In the future, however, I might just rename variables instead of using this function, since it's really not all that much more convenient to use this method. 

However, I find some issues with running particular lines-- these were areas that I planned to return to, but ultimately overlooked, so thank you for noticing them!

I agree with all of your suggestions, and plan to use these suggestions to improve my manuscript/ project. 

Thank you,
Hayley
